# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('perf_id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u5e8f\u53f7')),
                ('name', models.CharField(max_length=8, verbose_name='\u59d3\u540d')),
                ('team', models.CharField(choices=[('\u4e00\u5ba4', '\u4e00\u5ba4'), ('\u4e8c\u5ba4', '\u4e8c\u5ba4'), ('\u4e09\u5ba4', '\u4e09\u5ba4'), ('\u56e2\u961f', '\u56e2\u961f')], max_length=4, verbose_name='\u5ba4\u522b')),
                ('performance', models.FloatField(choices=[(15.0, '\u52a0\u67dc\u53f0/\u5c0f\u65f6'), (5.0, '\u6311\u884c\u674e/\u4ef6'), (20.0, '\u534f\u52a9481/\u5c0f\u65f6'), (10.0, '\u7ed3\u5173/\u73ed')], max_length=4, verbose_name='\u52a0\u5206\u9879')),
                ('values', models.FloatField(max_length=4, verbose_name='\u6570\u503c')),
                ('workload', models.FloatField(default=0.0, max_length=4, verbose_name='\u7ee9\u6548\u4eba\u6570')),
                ('point', models.FloatField(default=0.0, max_length=4, verbose_name='\u7ee9\u6548\u52a0\u5206')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='\u65e5\u671f')),
                ('verify', models.CharField(choices=[('\u7b49\u5f85\u5ba1\u6838', '\u7b49\u5f85\u5ba1\u6838'), ('\u672a\u901a\u8fc7\u5ba1\u6838', '\u672a\u901a\u8fc7\u5ba1\u6838'), ('\u5df2\u5ba1\u6838', '\u5df2\u5ba1\u6838')], default='\u7b49\u5f85\u5ba1\u6838', max_length=10, verbose_name='\u5ba1\u6838\u72b6\u6001')),
                ('verify_auth', models.CharField(blank=True, max_length=8)),
                ('verify_date', models.DateTimeField(blank=True)),
            ],
            options={
                'verbose_name': '\u6458\u8981',
                'verbose_name_plural': '\u7ee9\u6548\u767b\u8bb0',
            },
        ),
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='\u59d3\u540d')),
                ('team', models.CharField(choices=[('\u4e00\u5ba4', '\u4e00\u5ba4'), ('\u4e8c\u5ba4', '\u4e8c\u5ba4'), ('\u4e09\u5ba4', '\u4e09\u5ba4'), ('\u56e2\u961f', '\u56e2\u961f')], max_length=4, verbose_name='\u5ba4\u522b')),
                ('year', models.IntegerField(choices=[(2016, '2016')], verbose_name='\u5e74\u4efd')),
                ('month', models.IntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], verbose_name='\u6708\u4efd')),
                ('workload', models.FloatField(default=0.0, max_length=4, verbose_name='\u7ee9\u6548\u4eba\u6570')),
                ('point', models.FloatField(default=0.0, max_length=4, verbose_name='\u7ee9\u6548\u52a0\u5206')),
            ],
            options={
                'verbose_name': '\u7ee9\u6548',
                'verbose_name_plural': '\u7ee9\u6548\u7edf\u8ba1',
            },
        ),
    ]
