# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-27 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=8)),
                ('team', models.CharField(choices=[('\u4e00\u5ba4', '\u4e00\u5ba4'), ('\u4e8c\u5ba4', '\u4e8c\u5ba4'), ('\u4e09\u5ba4', '\u4e09\u5ba4'), ('\u56e2\u961f', '\u56e2\u961f')], max_length=4)),
                ('performance', models.FloatField(choices=[(15.0, '\u52a0\u67dc\u53f0/\u5c0f\u65f6'), (5.0, '\u6311\u884c\u674e/\u4ef6'), (20.0, '\u534f\u52a9481/\u5c0f\u65f6'), (10.0, '\u7ed3\u5173/\u73ed')], max_length=4)),
                ('values', models.FloatField(max_length=3)),
                ('workload', models.FloatField(default=0.0, max_length=4)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('verify', models.CharField(choices=[('\u7b49\u5f85\u5ba1\u6838', '\u7b49\u5f85\u5ba1\u6838'), ('\u672a\u901a\u8fc7\u5ba1\u6838', '\u672a\u901a\u8fc7\u5ba1\u6838'), ('\u5df2\u5ba1\u6838', '\u5df2\u5ba1\u6838')], default='\u5ba1\u6838\u9a8c\u8bc1', max_length=8)),
            ],
            options={
                'verbose_name': '\u7ee9\u6548\u767b\u8bb0',
                'verbose_name_plural': '\u7ee9\u6548\u767b\u8bb0',
            },
        ),
    ]
