# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-20 05:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addother',
            fields=[
                ('other_id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u5e8f\u53f7')),
                ('other_name', models.CharField(max_length=8, verbose_name='\u59d3\u540d')),
                ('other_team', models.CharField(choices=[('\u4e00\u5ba4', '\u4e00\u5ba4'), ('\u4e8c\u5ba4', '\u4e8c\u5ba4'), ('\u4e09\u5ba4', '\u4e09\u5ba4'), ('\u56e2\u961f', '\u56e2\u961f')], max_length=4, verbose_name='\u5ba4\u522b')),
                ('airline', models.CharField(choices=[(252.001, 'AF'), (72.006, 'BR'), (72.007, 'CI'), (72.002, 'JL'), (84.002, 'KA'), (72.004, 'KE'), (72.001, 'MH'), (72.005, 'OZ'), (108.001, 'OZ370+306'), (115.201, 'OZ356+306'), (100.801, 'OZ358+306'), (84.001, 'SU'), (78.001, 'SQ'), (72.003, 'TG'), (78.002, 'VN'), (93.601, 'VN549'), (109.201, 'VN549\u7559\u5b88')], max_length=10, verbose_name='\u5916\u822a')),
                ('taskclass', models.FloatField(choices=[(0.0, '\u65e0'), (1.3, '\u7ec4\u957f'), (1.2, 'C\u8231'), (1.1, 'Y\u8231')], max_length=4, verbose_name='\u4efb\u52a1\u8231\u4f4d')),
                ('taskone', models.FloatField(choices=[(0.0, '\u65e0'), (10.0, '\u7ed3\u5173'), (15.0, '\u9001\u673a')], max_length=4, verbose_name='\u7ed3\u9001\u673a')),
                ('tasktwo', models.FloatField(choices=[(0.0, '\u65e0'), (10.1, '\u6570\u7968'), (10.2, '\u7535\u62a5'), (10.3, '\u62c9Q'), (20.0, 'PRE-FLT'), (20.1, 'POST-FLT')], max_length=8, verbose_name='\u5176\u4ed6\u4efb\u52a11')),
                ('taskthree', models.FloatField(choices=[(0.0, '\u65e0'), (10.1, '\u6570\u7968'), (10.2, '\u7535\u62a5'), (10.3, '\u62c9Q'), (20.0, 'PRE-FLT'), (20.1, 'POST-FLT')], max_length=8, verbose_name='\u5176\u4ed6\u4efb\u52a12')),
                ('taskfour', models.FloatField(choices=[(0.0, '\u65e0'), (10.1, '\u6570\u7968'), (10.2, '\u7535\u62a5'), (10.3, '\u62c9Q'), (20.0, 'PRE-FLT'), (20.1, 'POST-FLT')], max_length=8, verbose_name='\u5176\u4ed6\u4efb\u52a13')),
                ('other_workload', models.FloatField(default=0.0, max_length=4, verbose_name='\u7ee9\u6548\u4eba\u6570')),
                ('other_date', models.DateField(default=django.utils.timezone.now, verbose_name='\u65e5\u671f')),
                ('other_verify', models.CharField(choices=[('\u7b49\u5f85\u5ba1\u6838', '\u7b49\u5f85\u5ba1\u6838'), ('\u672a\u901a\u8fc7', '\u672a\u901a\u8fc7'), ('\u5df2\u5ba1\u6838', '\u5df2\u5ba1\u6838')], default='\u7b49\u5f85\u5ba1\u6838', max_length=10, verbose_name='\u5ba1\u6838\u72b6\u6001')),
                ('other_auth', models.CharField(default='NULL', max_length=8, verbose_name='\u5ba1\u6838\u4eba')),
                ('other_verifydate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u63d0\u4ea4/\u5ba1\u6838\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5916\u822a\u7ee9\u6548',
                'verbose_name_plural': '\u5916\u822a\u7ee9\u6548\u767b\u8bb0',
            },
        ),
        migrations.CreateModel(
            name='Countother',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_name', models.CharField(max_length=8, verbose_name='\u59d3\u540d')),
                ('other_team', models.CharField(choices=[('\u4e00\u5ba4', '\u4e00\u5ba4'), ('\u4e8c\u5ba4', '\u4e8c\u5ba4'), ('\u4e09\u5ba4', '\u4e09\u5ba4'), ('\u56e2\u961f', '\u56e2\u961f')], max_length=4, verbose_name='\u5ba4\u522b')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='\u8d77\u59cb\u65e5\u671f')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='\u622a\u6b62\u65e5\u671f')),
                ('other_workload', models.FloatField(default=0.0, max_length=4, verbose_name='\u7ee9\u6548\u4eba\u6570')),
            ],
            options={
                'verbose_name': '\u5916\u822a\u7edf\u8ba1',
                'verbose_name_plural': '\u5916\u822a\u7edf\u8ba1',
            },
        ),
        migrations.AddField(
            model_name='add',
            name='performancethree',
            field=models.FloatField(choices=[(5.0, '\u6311\u884c\u674e   \u4ef6/1\u6b21'), (20.0, '\u7f51\u4e0a\u503c\u673a/\u5c0f\u65f6'), (20.1, '\u56e2\u961f\u6258\u8fd0/\u5c0f\u65f6'), (10.0, '\u503c\u591c\u7ed3\u5173/\u73ed\uff08\u8bf7\u5907\u6ce8\u822a\u73ed\uff09'), (10.1, '\u503c\u591c\u6570\u7968/\u6b21'), (15.0, '\u5173\u5c01/\u73ed\uff08\u8bf7\u5907\u6ce8\u822a\u73ed\uff09'), (20.2, '\u8d85\u5927/\u5c0f\u65f6'), (20.3, '\u5361\u5927\u5305/\u5c0f\u65f6'), (20.4, 'Q\u53e3\u5f15\u5bfc/\u5c0f\u65f6'), (1.0, '\u52a0CZ\u67dc\u53f0/\u5c0f\u65f6'), (1.1, '\u5ef6\u65f6\u4e0b\u73ed/\u5c0f\u65f6'), (1.2, '\u534f\u52a9481\u5de5\u4f5c/\u5c0f\u65f6\uff08\u5982\u9000\u5173\u3001\u9001\u65c5\u5ba2\u3001\u5230B\u533a\u62ff\u884c\u674e\u7b49\uff09\uff08\u8bf7\u5907\u6ce8\uff09'), (1.3, '\u5176\u4ed6   /\u5c0f\u65f6/\u6b21/\u73ed\uff08\u8bf7\u5907\u6ce8\uff09')], default=0, max_length=4, verbose_name='\u9879\u76ee3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add',
            name='performancetwo',
            field=models.FloatField(choices=[(5.0, '\u6311\u884c\u674e   \u4ef6/1\u6b21'), (20.0, '\u7f51\u4e0a\u503c\u673a/\u5c0f\u65f6'), (20.1, '\u56e2\u961f\u6258\u8fd0/\u5c0f\u65f6'), (10.0, '\u503c\u591c\u7ed3\u5173/\u73ed\uff08\u8bf7\u5907\u6ce8\u822a\u73ed\uff09'), (10.1, '\u503c\u591c\u6570\u7968/\u6b21'), (15.0, '\u5173\u5c01/\u73ed\uff08\u8bf7\u5907\u6ce8\u822a\u73ed\uff09'), (20.2, '\u8d85\u5927/\u5c0f\u65f6'), (20.3, '\u5361\u5927\u5305/\u5c0f\u65f6'), (20.4, 'Q\u53e3\u5f15\u5bfc/\u5c0f\u65f6'), (1.0, '\u52a0CZ\u67dc\u53f0/\u5c0f\u65f6'), (1.1, '\u5ef6\u65f6\u4e0b\u73ed/\u5c0f\u65f6'), (1.2, '\u534f\u52a9481\u5de5\u4f5c/\u5c0f\u65f6\uff08\u5982\u9000\u5173\u3001\u9001\u65c5\u5ba2\u3001\u5230B\u533a\u62ff\u884c\u674e\u7b49\uff09\uff08\u8bf7\u5907\u6ce8\uff09'), (1.3, '\u5176\u4ed6   /\u5c0f\u65f6/\u6b21/\u73ed\uff08\u8bf7\u5907\u6ce8\uff09')], default=0, max_length=4, verbose_name='\u9879\u76ee2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add',
            name='valuesthree',
            field=models.FloatField(default=0, max_length=4, verbose_name='\u6570\u503c'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='add',
            name='valuestwo',
            field=models.FloatField(default=0, max_length=4, verbose_name='\u6570\u503c'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='add',
            name='performance',
            field=models.FloatField(choices=[(5.0, '\u6311\u884c\u674e   \u4ef6/1\u6b21'), (20.0, '\u7f51\u4e0a\u503c\u673a/\u5c0f\u65f6'), (20.1, '\u56e2\u961f\u6258\u8fd0/\u5c0f\u65f6'), (10.0, '\u503c\u591c\u7ed3\u5173/\u73ed\uff08\u8bf7\u5907\u6ce8\u822a\u73ed\uff09'), (10.1, '\u503c\u591c\u6570\u7968/\u6b21'), (15.0, '\u5173\u5c01/\u73ed\uff08\u8bf7\u5907\u6ce8\u822a\u73ed\uff09'), (20.2, '\u8d85\u5927/\u5c0f\u65f6'), (20.3, '\u5361\u5927\u5305/\u5c0f\u65f6'), (20.4, 'Q\u53e3\u5f15\u5bfc/\u5c0f\u65f6'), (1.0, '\u52a0CZ\u67dc\u53f0/\u5c0f\u65f6'), (1.1, '\u5ef6\u65f6\u4e0b\u73ed/\u5c0f\u65f6'), (1.2, '\u534f\u52a9481\u5de5\u4f5c/\u5c0f\u65f6\uff08\u5982\u9000\u5173\u3001\u9001\u65c5\u5ba2\u3001\u5230B\u533a\u62ff\u884c\u674e\u7b49\uff09\uff08\u8bf7\u5907\u6ce8\uff09'), (1.3, '\u5176\u4ed6   /\u5c0f\u65f6/\u6b21/\u73ed\uff08\u8bf7\u5907\u6ce8\uff09')], max_length=4, verbose_name='\u9879\u76ee1'),
        ),
        migrations.AlterField(
            model_name='add',
            name='verify',
            field=models.CharField(choices=[('\u7b49\u5f85\u5ba1\u6838', '\u7b49\u5f85\u5ba1\u6838'), ('\u672a\u901a\u8fc7', '\u672a\u901a\u8fc7'), ('\u5df2\u5ba1\u6838', '\u5df2\u5ba1\u6838')], default='\u7b49\u5f85\u5ba1\u6838', max_length=10, verbose_name='\u5ba1\u6838\u72b6\u6001'),
        ),
    ]
