# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-26 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='countother',
            name='other_point',
            field=models.FloatField(default=0.0, max_length=4, verbose_name='\u7ee9\u6548\u52a0\u5206'),
        ),
        migrations.AlterField(
            model_name='countother',
            name='other_workload',
            field=models.FloatField(default=0.0, max_length=8, verbose_name='\u7ee9\u6548\u4eba\u6570'),
        ),
    ]
