# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-26 17:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addother',
            name='task_values',
            field=models.FloatField(default=0, max_length=4, verbose_name='\u5176\u4ed6\u4efb\u52a1\u503c'),
        ),
    ]
