# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-27 09:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add',
            old_name='id',
            new_name='perf_id',
        ),
    ]
