# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-23 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='comment',
            field=models.TextField(default='\u65e0', max_length=60, verbose_name='\u5907\u6ce8'),
        ),
        migrations.AlterField(
            model_name='add',
            name='performance',
            field=models.FloatField(choices=[(5.0, '\u6311\u884c\u674e \u4ef6/1\u6b21'), (20.0, '\u7f51\u4e0a\u503c\u673a/\u5c0f\u65f6'), (20.0, '\u56e2\u961f\u6258\u8fd0/\u5c0f\u65f6'), (10.0, '\u503c\u591c\u7ed3\u5173/\u73ed'), (10.0, '\u503c\u591c\u6570\u7968/\u6b21'), (15.0, '\u5173\u5c01/\u73ed'), (20.0, '\u8d85\u5927/\u5c0f\u65f6'), (20.0, '\u5361\u5927\u5305/\u5c0f\u65f6'), (20.0, 'Q\u53e3\u5f15\u5bfc/\u5c0f\u65f6'), (1.0, '\u52a0CZ\u67dc\u53f0/\u5c0f\u65f6'), (1.0, '\u5ef6\u65f6\u4e0b\u73ed/\u5c0f\u65f6'), (1.0, '\u534f\u52a9481\u5de5\u4f5c/\u5c0f\u65f6\uff08\u5982\u9000\u5173\u3001\u9001\u65c5\u5ba2\u3001\u5230B\u533a\u62ff\u884c\u674e\u7b49\uff09\uff08\u8bf7\u5907\u6ce8\uff09'), (1.0, '\u5176\u4ed6/\u5c0f\u65f6/\u6b21/\u73ed\uff08\u8bf7\u5907\u6ce8\uff09')], max_length=4, verbose_name='\u52a0\u5206\u9879'),
        ),
    ]
