# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='verify_auth',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='add',
            name='verify_date',
            field=models.DateTimeField(null=True),
        ),
    ]
