# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-26 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0002_auto_20161026_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addother',
            name='taskfive',
            field=models.FloatField(choices=[(0.0, '\u65e0'), (0.501, '\u52a0\u5916\u822a\u67dc\u53f0\uff08\u8bf7\u5728\u4e0b\u65b9\u586b\u5199\u65f6\u957f\uff0c\u5355\u4f4d\u201c\u5c0f\u65f6\u201d\uff09'), (0.502, '\u5ef6\u8bef\u7559\u5b88\uff08\u8bf7\u5728\u4e0b\u65b9\u586b\u5199\u65f6\u957f\uff0c\u5355\u4f4d\u201c\u5c0f\u65f6\u201d\uff09'), (5.001, '\u5916\u822a\u6311\u884c\u674e\u4ef6\u6570\uff08\u8bf7\u5728\u4e0b\u65b9\u586b\u5199\u4ef6\u6570\uff0c\u5355\u4f4d\u201c\u4ef6/\u6bcf\u6b21\u201d\uff09'), (15.002, '\u8d27\u673a\u7ed3\u5173\uff08\u8bf7\u5728\u4e0b\u65b9\u586b\u5199\u73ed\u6b21\uff0c\u53ea\u5141\u8bb8\u6574\u6570\uff0c\u5355\u4f4d\u201c\u73ed\u201d\uff09')], default=0.0, max_length=8, verbose_name='\u5176\u4ed6\u4efb\u52a1'),
        ),
    ]
