# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-20 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0002_auto_20160921_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='verify_auth',
            field=models.CharField(default='\u672a\u5ba1\u6838', editable=False, max_length=8),
        ),
        migrations.AlterField(
            model_name='add',
            name='verify_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
