# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-25 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0002_auto_20170325_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add',
            name='team',
        ),
        migrations.RemoveField(
            model_name='addother',
            name='other_team',
        ),
    ]
