# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-28 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0002_auto_20160827_1730'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='add',
            options={'verbose_name': '\u6458\u8981', 'verbose_name_plural': '\u7ee9\u6548\u767b\u8bb0'},
        ),
        migrations.AddField(
            model_name='add',
            name='point',
            field=models.FloatField(default=0.0, max_length=3, verbose_name='\u7ee9\u6548\u52a0\u5206'),
        ),
        migrations.AlterField(
            model_name='add',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='add',
            name='name',
            field=models.CharField(max_length=8, verbose_name='\u59d3\u540d'),
        ),
        migrations.AlterField(
            model_name='add',
            name='perf_id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='\u5e8f\u53f7'),
        ),
        migrations.AlterField(
            model_name='add',
            name='performance',
            field=models.FloatField(choices=[(15.0, '\u52a0\u67dc\u53f0/\u5c0f\u65f6'), (5.0, '\u6311\u884c\u674e/\u4ef6'), (20.0, '\u534f\u52a9481/\u5c0f\u65f6'), (10.0, '\u7ed3\u5173/\u73ed')], max_length=4, verbose_name='\u52a0\u5206\u9879'),
        ),
        migrations.AlterField(
            model_name='add',
            name='team',
            field=models.CharField(choices=[('\u4e00\u5ba4', '\u4e00\u5ba4'), ('\u4e8c\u5ba4', '\u4e8c\u5ba4'), ('\u4e09\u5ba4', '\u4e09\u5ba4'), ('\u56e2\u961f', '\u56e2\u961f')], max_length=4, verbose_name='\u5ba4\u522b'),
        ),
        migrations.AlterField(
            model_name='add',
            name='values',
            field=models.FloatField(max_length=4, verbose_name='\u52a0\u5206\u6570\u503c'),
        ),
        migrations.AlterField(
            model_name='add',
            name='verify',
            field=models.BooleanField(verbose_name='\u5ba1\u6838\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='add',
            name='workload',
            field=models.FloatField(default=0.0, max_length=4, verbose_name='\u7ee9\u6548\u4eba\u6570'),
        ),
    ]
