# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-20 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0003_auto_20161020_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addother',
            name='airline',
            field=models.FloatField(choices=[(252.001, 'AF'), (72.006, 'BR'), (72.007, 'CI'), (72.002, 'JL'), (84.002, 'KA'), (72.004, 'KE'), (72.001, 'MH'), (72.005, 'OZ'), (108.001, 'OZ370+306'), (115.201, 'OZ356+306'), (100.801, 'OZ358+306'), (84.001, 'SU'), (78.001, 'SQ'), (72.003, 'TG'), (78.002, 'VN'), (93.601, 'VN549'), (109.201, 'VN549\u7559\u5b88')], max_length=10, verbose_name='\u5916\u822a'),
        ),
        migrations.AlterField(
            model_name='addother',
            name='taskclass',
            field=models.FloatField(choices=[(0.0, '\u65e0'), (1.3, '\u7ec4\u957f'), (1.2, 'C\u8231'), (1.1, 'Y\u8231')], default=0.0, max_length=4, verbose_name='\u4efb\u52a1\u8231\u4f4d'),
        ),
        migrations.AlterField(
            model_name='addother',
            name='taskfour',
            field=models.FloatField(choices=[(0.0, '\u65e0'), (10.1, '\u6570\u7968'), (10.2, '\u7535\u62a5'), (10.3, '\u62c9Q'), (20.0, 'PRE-FLT'), (20.1, 'POST-FLT')], default=0.0, max_length=8, verbose_name='\u5176\u4ed6\u4efb\u52a13'),
        ),
        migrations.AlterField(
            model_name='addother',
            name='taskone',
            field=models.FloatField(choices=[(0.0, '\u65e0'), (10.0, '\u7ed3\u5173'), (15.0, '\u9001\u673a')], default=0.0, max_length=4, verbose_name='\u7ed3\u9001\u673a'),
        ),
        migrations.AlterField(
            model_name='addother',
            name='taskthree',
            field=models.FloatField(choices=[(0.0, '\u65e0'), (10.1, '\u6570\u7968'), (10.2, '\u7535\u62a5'), (10.3, '\u62c9Q'), (20.0, 'PRE-FLT'), (20.1, 'POST-FLT')], default=0.0, max_length=8, verbose_name='\u5176\u4ed6\u4efb\u52a12'),
        ),
        migrations.AlterField(
            model_name='addother',
            name='tasktwo',
            field=models.FloatField(choices=[(0.0, '\u65e0'), (10.1, '\u6570\u7968'), (10.2, '\u7535\u62a5'), (10.3, '\u62c9Q'), (20.0, 'PRE-FLT'), (20.1, 'POST-FLT')], default=0.0, max_length=8, verbose_name='\u5176\u4ed6\u4efb\u52a11'),
        ),
    ]
