# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-25 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0003_auto_20170325_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='team',
            field=models.CharField(default=1, editable=False, max_length=8, verbose_name='\u5ba4\u522b'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='addother',
            name='other_team',
            field=models.CharField(default=1, editable=False, max_length=8, verbose_name='\u5ba4\u522b'),
            preserve_default=False,
        ),
    ]
