# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-20 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0004_auto_20161020_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='performance',
            field=models.FloatField(choices=[(0.0, '\u65e0'), (5.0, '\u6311\u884c\u674e   \u4ef6/1\u6b21'), (20.0, '\u7f51\u4e0a\u503c\u673a/\u5c0f\u65f6'), (20.1, '\u56e2\u961f\u6258\u8fd0/\u5c0f\u65f6'), (10.0, '\u503c\u591c\u7ed3\u5173/\u73ed\uff08\u8bf7\u5907\u6ce8\u822a\u73ed\uff09'), (10.1, '\u503c\u591c\u6570\u7968/\u6b21'), (15.0, '\u5173\u5c01/\u73ed\uff08\u8bf7\u5907\u6ce8\u822a\u73ed\uff09'), (20.2, '\u8d85\u5927/\u5c0f\u65f6'), (20.3, '\u5361\u5927\u5305/\u5c0f\u65f6'), (20.4, 'Q\u53e3\u5f15\u5bfc/\u5c0f\u65f6'), (1.0, '\u52a0CZ\u67dc\u53f0/\u5c0f\u65f6'), (1.1, '\u5ef6\u65f6\u4e0b\u73ed/\u5c0f\u65f6'), (1.2, '\u534f\u52a9481\u5de5\u4f5c/\u5c0f\u65f6\uff08\u5982\u9000\u5173\u3001\u9001\u65c5\u5ba2\u3001\u5230B\u533a\u62ff\u884c\u674e\u7b49\uff09\uff08\u8bf7\u5907\u6ce8\uff09'), (1.3, '\u5176\u4ed6   /\u5c0f\u65f6/\u6b21/\u73ed\uff08\u8bf7\u5907\u6ce8\uff09')], default=0.0, max_length=4, verbose_name='\u4efb\u52a11'),
        ),
        migrations.AlterField(
            model_name='add',
            name='performancethree',
            field=models.FloatField(choices=[(0.0, '\u65e0'), (5.0, '\u6311\u884c\u674e   \u4ef6/1\u6b21'), (20.0, '\u7f51\u4e0a\u503c\u673a/\u5c0f\u65f6'), (20.1, '\u56e2\u961f\u6258\u8fd0/\u5c0f\u65f6'), (10.0, '\u503c\u591c\u7ed3\u5173/\u73ed\uff08\u8bf7\u5907\u6ce8\u822a\u73ed\uff09'), (10.1, '\u503c\u591c\u6570\u7968/\u6b21'), (15.0, '\u5173\u5c01/\u73ed\uff08\u8bf7\u5907\u6ce8\u822a\u73ed\uff09'), (20.2, '\u8d85\u5927/\u5c0f\u65f6'), (20.3, '\u5361\u5927\u5305/\u5c0f\u65f6'), (20.4, 'Q\u53e3\u5f15\u5bfc/\u5c0f\u65f6'), (1.0, '\u52a0CZ\u67dc\u53f0/\u5c0f\u65f6'), (1.1, '\u5ef6\u65f6\u4e0b\u73ed/\u5c0f\u65f6'), (1.2, '\u534f\u52a9481\u5de5\u4f5c/\u5c0f\u65f6\uff08\u5982\u9000\u5173\u3001\u9001\u65c5\u5ba2\u3001\u5230B\u533a\u62ff\u884c\u674e\u7b49\uff09\uff08\u8bf7\u5907\u6ce8\uff09'), (1.3, '\u5176\u4ed6   /\u5c0f\u65f6/\u6b21/\u73ed\uff08\u8bf7\u5907\u6ce8\uff09')], default=0.0, max_length=4, verbose_name='\u4efb\u52a13'),
        ),
        migrations.AlterField(
            model_name='add',
            name='performancetwo',
            field=models.FloatField(choices=[(0.0, '\u65e0'), (5.0, '\u6311\u884c\u674e   \u4ef6/1\u6b21'), (20.0, '\u7f51\u4e0a\u503c\u673a/\u5c0f\u65f6'), (20.1, '\u56e2\u961f\u6258\u8fd0/\u5c0f\u65f6'), (10.0, '\u503c\u591c\u7ed3\u5173/\u73ed\uff08\u8bf7\u5907\u6ce8\u822a\u73ed\uff09'), (10.1, '\u503c\u591c\u6570\u7968/\u6b21'), (15.0, '\u5173\u5c01/\u73ed\uff08\u8bf7\u5907\u6ce8\u822a\u73ed\uff09'), (20.2, '\u8d85\u5927/\u5c0f\u65f6'), (20.3, '\u5361\u5927\u5305/\u5c0f\u65f6'), (20.4, 'Q\u53e3\u5f15\u5bfc/\u5c0f\u65f6'), (1.0, '\u52a0CZ\u67dc\u53f0/\u5c0f\u65f6'), (1.1, '\u5ef6\u65f6\u4e0b\u73ed/\u5c0f\u65f6'), (1.2, '\u534f\u52a9481\u5de5\u4f5c/\u5c0f\u65f6\uff08\u5982\u9000\u5173\u3001\u9001\u65c5\u5ba2\u3001\u5230B\u533a\u62ff\u884c\u674e\u7b49\uff09\uff08\u8bf7\u5907\u6ce8\uff09'), (1.3, '\u5176\u4ed6   /\u5c0f\u65f6/\u6b21/\u73ed\uff08\u8bf7\u5907\u6ce8\uff09')], default=0.0, max_length=4, verbose_name='\u4efb\u52a12'),
        ),
        migrations.AlterField(
            model_name='add',
            name='values',
            field=models.FloatField(default=0, max_length=4, verbose_name='\u6570\u503c1'),
        ),
        migrations.AlterField(
            model_name='add',
            name='valuesthree',
            field=models.FloatField(default=0, max_length=4, verbose_name='\u6570\u503c3'),
        ),
        migrations.AlterField(
            model_name='add',
            name='valuestwo',
            field=models.FloatField(default=0, max_length=4, verbose_name='\u6570\u503c2'),
        ),
    ]
