# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-26 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0004_auto_20170325_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addother',
            name='airline',
            field=models.FloatField(choices=[(252.0001, 'AF107'), (72.0001, 'BR708'), (72.0002, 'BR798'), (72.0003, 'B7520'), (72.0004, 'CI522'), (72.0005, 'JL088'), (112.0001, 'KA789\u65e9\u4e0a\u67dc\u53f0'), (84.0001, 'KA783'), (84.0002, 'KA789'), (72.0006, 'KE866'), (72.0007, 'MH377'), (72.0008, '\u5348OZ370'), (72.0009, '\u665aOZ356'), (72.0011, '\u665aOZ358'), (72.0012, '\u5348OZ306'), (72.0015, '\u665aOZ306'), (108.0001, '\u5348OZ370+\u5348306'), (115.2001, '\u665aOZ356+\u665a306'), (100.8001, '\u665aOZ358+\u665a306'), (84.0003, 'SU221'), (78.0001, 'SQ851'), (78.0002, 'SQ853'), (72.0013, 'TG669'), (72.0014, 'TG679'), (78.0003, 'VN503'), (78.0004, 'VN507'), (109.2001, 'VN503\u7559\u5b88'), (93.6001, 'VN549')], max_length=10, verbose_name='\u5916\u822a'),
        ),
    ]
