# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-02 01:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0004_auto_20160831_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add',
            name='verify',
            field=models.CharField(choices=[('\u7b49\u5f85\u5ba1\u6838', '\u7b49\u5f85\u5ba1\u6838'), ('\u672a\u901a\u8fc7\u5ba1\u6838', '\u672a\u901a\u8fc7\u5ba1\u6838'), ('\u5df2\u5ba1\u6838', '\u5df2\u5ba1\u6838')], default='\u7b49\u5f85\u5ba1\u6838', max_length=8, verbose_name='\u5ba1\u6838\u72b6\u6001'),
        ),
        migrations.AlterField(
            model_name='count',
            name='month',
            field=models.IntegerField(choices=[(1, '01'), (2, '02'), (3, '03'), (4, '04'), (5, '05'), (6, '06'), (7, '07'), (8, '08'), (9, '09'), (10, '10'), (11, '11'), (12, '12')], verbose_name='\u6708\u4efd'),
        ),
        migrations.AlterField(
            model_name='count',
            name='year',
            field=models.IntegerField(choices=[(2016, '2016')], verbose_name='\u5e74\u4efd'),
        ),
    ]
