# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-20 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0005_auto_20161020_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addother',
            name='taskfour',
            field=models.FloatField(choices=[(0.0, '\u65e0'), (10.002, '\u6570\u7968'), (10.003, '\u7535\u62a5'), (10.004, '\u62c9Q'), (20.001, 'PRE-FLT'), (20.002, 'POST-FLT')], default=0.0, max_length=8, verbose_name='\u5176\u4ed6\u4efb\u52a13'),
        ),
        migrations.AlterField(
            model_name='addother',
            name='taskone',
            field=models.FloatField(choices=[(0.0, '\u65e0'), (10.001, '\u7ed3\u5173'), (15.001, '\u9001\u673a')], default=0.0, max_length=8, verbose_name='\u7ed3\u9001\u673a'),
        ),
        migrations.AlterField(
            model_name='addother',
            name='taskthree',
            field=models.FloatField(choices=[(0.0, '\u65e0'), (10.002, '\u6570\u7968'), (10.003, '\u7535\u62a5'), (10.004, '\u62c9Q'), (20.001, 'PRE-FLT'), (20.002, 'POST-FLT')], default=0.0, max_length=8, verbose_name='\u5176\u4ed6\u4efb\u52a12'),
        ),
        migrations.AlterField(
            model_name='addother',
            name='tasktwo',
            field=models.FloatField(choices=[(0.0, '\u65e0'), (10.002, '\u6570\u7968'), (10.003, '\u7535\u62a5'), (10.004, '\u62c9Q'), (20.001, 'PRE-FLT'), (20.002, 'POST-FLT')], default=0.0, max_length=8, verbose_name='\u5176\u4ed6\u4efb\u52a11'),
        ),
    ]
