# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-20 06:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0006_auto_20161020_1442'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countother',
            old_name='other_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='countother',
            old_name='other_team',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='countother',
            old_name='other_workload',
            new_name='workload',
        ),
    ]
