# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-20 07:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0007_auto_20161020_1458'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countother',
            old_name='name',
            new_name='other_name',
        ),
        migrations.RenameField(
            model_name='countother',
            old_name='team',
            new_name='other_team',
        ),
        migrations.RenameField(
            model_name='countother',
            old_name='workload',
            new_name='other_workload',
        ),
    ]
