# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-20 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0008_auto_20161020_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='add',
            name='supervisor',
            field=models.CharField(choices=[('\u4e00\u5ba4', '\u4e00\u5ba4\uff08\u7f57\u5fd7\u748b\u3001\u6bdb\u601d\u5b34\u3001\u8d75\u81e3\u7b49\uff09'), ('\u4e8c\u5ba4', '\u4e8c\u5ba4\uff08\u59da\u79cb\u7115\u3001\u5218\u5468\u654f\u3001\u718a\u8f89\u3001\u6768\u4ef2\u8d24\u7b49\uff09'), ('\u4e09\u5ba4', '\u4e09\u5ba4\uff08\u5362\u4e98\u3001\u6e29\u5fd7\u68ee\u3001\u5434\u5a55\u73b2\u3001\u5218\u5072\u7fc0\u3001\u738b\u4f73\u3001\u9ec4\u6c5d\u535a\u7b49\uff09'), ('\u56e2\u961f', '\u56e2\u961f\uff08\u5434\u73b2\u3001\u6881\u826f\u7b49\uff09')], default=0, max_length=4, verbose_name='\u6307\u6d3e\u5ba4'),
            preserve_default=False,
        ),
    ]
