# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-20 14:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perf', '0011_auto_20161020_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countother',
            name='other_team',
            field=models.CharField(choices=[('\u5168\u90e8', '\u5168\u90e8'), ('\u4e00\u5ba4', '\u4e00\u5ba4'), ('\u4e8c\u5ba4', '\u4e8c\u5ba4'), ('\u4e09\u5ba4', '\u4e09\u5ba4'), ('\u56e2\u961f', '\u56e2\u961f')], max_length=4, verbose_name='\u5ba4\u522b'),
        ),
    ]
