# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-25 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u5e8f\u53f7')),
                ('name', models.CharField(max_length=8, verbose_name='\u59d3\u540d')),
                ('eid', models.IntegerField(verbose_name='\u5458\u5de5\u53f7')),
                ('wid', models.IntegerField(verbose_name='\u5de5\u4f5c\u53f7')),
                ('group', models.CharField(choices=[('\u4e00\u5ba41\u7ec4', '\u4e00\u5ba41\u7ec4'), ('\u4e00\u5ba42\u7ec4', '\u4e00\u5ba42\u7ec4'), ('\u4e00\u5ba43\u7ec4', '\u4e00\u5ba43\u7ec4'), ('\u4e8c\u5ba44\u7ec4', '\u4e8c\u5ba44\u7ec4'), ('\u4e8c\u5ba45\u7ec4', '\u4e8c\u5ba45\u7ec4'), ('\u4e8c\u5ba46\u7ec4', '\u4e8c\u5ba46\u7ec4'), ('\u4e09\u5ba47\u7ec4', '\u4e09\u5ba47\u7ec4'), ('\u4e09\u5ba48\u7ec4', '\u4e09\u5ba48\u7ec4'), ('\u4e09\u5ba49\u7ec4', '\u4e09\u5ba49\u7ec4'), ('\u56e2\u961f1\u7ec4', '\u56e2\u961f1\u7ec4'), ('\u56e2\u961f2\u7ec4', '\u56e2\u961f2\u7ec4'), ('\u56e2\u961f3\u7ec4', '\u56e2\u961f3\u7ec4')], max_length=8, verbose_name='\u56e2\u961f')),
                ('birth', models.DateField(verbose_name='\u751f\u65e5')),
                ('eqmanage', models.IntegerField(choices=[(0, 'N'), (1, 'Y')], default=0, verbose_name='\u8bbe\u5907\u7ba1\u7406')),
                ('assistant', models.IntegerField(choices=[(0, 'N'), (1, 'Y')], default=0, verbose_name='\u5916\u822a\u52a9\u7406')),
                ('groupleader', models.IntegerField(choices=[(0, 'N'), (1, 'Y')], default=0, verbose_name='\u7ec4\u957f')),
                ('typing', models.IntegerField(choices=[(0, 'N'), (1, 'Y')], default=0, verbose_name='\u6253\u5b57')),
                ('counting', models.IntegerField(choices=[(0, 'N'), (1, 'Y')], default=0, verbose_name='\u6570\u7968')),
                ('accountmanage', models.IntegerField(choices=[(0, 'N'), (1, 'Y')], default=0, verbose_name='\u8d22\u52a1')),
                ('courseware', models.IntegerField(choices=[(0, 'N'), (1, 'Y')], default=0, verbose_name='\u8bfe\u4ef6\u5236\u4f5c')),
                ('af', models.IntegerField(choices=[(0, 'N'), (1, 'Y')], default=0)),
                ('br', models.IntegerField(choices=[(0, 'N'), (1, 'Y')], default=0)),
                ('ci', models.IntegerField(choices=[(0, 'N'), (1, 'Y')], default=0)),
                ('jl', models.IntegerField(choices=[(0, 'N'), (1, 'Y')], default=0)),
                ('ka', models.IntegerField(choices=[(0, 'N'), (1, 'Y')], default=0)),
                ('ke', models.IntegerField(choices=[(0, 'N'), (1, 'Y')], default=0)),
                ('mh', models.IntegerField(choices=[(0, 'N'), (1, 'Y')], default=0)),
                ('oz', models.IntegerField(choices=[(0, 'N'), (1, 'Y')], default=0)),
                ('su', models.IntegerField(choices=[(0, 'N'), (1, 'Y')], default=0)),
                ('sq', models.IntegerField(choices=[(0, 'N'), (1, 'Y')], default=0)),
                ('tg', models.IntegerField(choices=[(0, 'N'), (1, 'Y')], default=0)),
                ('vn', models.IntegerField(choices=[(0, 'N'), (1, 'Y')], default=0)),
                ('status', models.CharField(choices=[('\u5728\u804c', '\u5728\u804c'), ('\u501f\u8c03', '\u501f\u8c03'), ('\u75c5\u4ea7\u5047', '\u75c5\u4ea7\u5047'), ('\u79bb\u804c', '\u79bb\u804c')], max_length=4, verbose_name='\u72b6\u6001')),
            ],
            options={
                'verbose_name': '\u5458\u5de5\u6863\u6848',
                'verbose_name_plural': '\u5458\u5de5\u6863\u6848',
            },
        ),
    ]
