# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-03-25 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Count',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, verbose_name='\u59d3\u540d')),
                ('team', models.CharField(max_length=4, verbose_name='\u5ba4\u522b')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='\u8d77\u59cb\u65e5\u671f')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='\u622a\u6b62\u65e5\u671f')),
                ('workload', models.FloatField(default=0.0, max_length=4, verbose_name='\u7ee9\u6548\u4eba\u6570')),
                ('point', models.FloatField(default=0.0, max_length=4, verbose_name='\u7ee9\u6548\u52a0\u5206')),
            ],
            options={
                'verbose_name': '\u7ee9\u6548\u7edf\u8ba1',
                'verbose_name_plural': '\u7ee9\u6548\u7edf\u8ba1',
            },
        ),
        migrations.CreateModel(
            name='Countother',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_name', models.CharField(max_length=8, verbose_name='\u59d3\u540d')),
                ('other_team', models.CharField(max_length=4, verbose_name='\u5ba4\u522b')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='\u8d77\u59cb\u65e5\u671f')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='\u622a\u6b62\u65e5\u671f')),
                ('other_workload', models.FloatField(default=0.0, max_length=8, verbose_name='\u7ee9\u6548\u4eba\u6570')),
                ('other_point', models.FloatField(default=0.0, max_length=4, verbose_name='\u7ee9\u6548\u52a0\u5206')),
                ('ci', models.IntegerField(default=0, verbose_name='ci\u6b21\u6570')),
                ('ka', models.IntegerField(default=0, verbose_name='ka\u6b21\u6570')),
                ('customsoz', models.IntegerField(default=0, verbose_name='oz\u7ed3\u5173')),
                ('customssq', models.IntegerField(default=0, verbose_name='sq\u7ed3\u5173')),
                ('postsq', models.IntegerField(default=0, verbose_name='sq-post')),
            ],
            options={
                'verbose_name': '\u5916\u822a\u7edf\u8ba1',
                'verbose_name_plural': '\u5916\u822a\u7edf\u8ba1',
            },
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u5e8f\u53f7')),
                ('name', models.CharField(max_length=8, verbose_name='\u59d3\u540d')),
                ('eid', models.IntegerField(verbose_name='\u5458\u5de5\u53f7')),
                ('wid', models.IntegerField(verbose_name='\u5de5\u4f5c\u53f7')),
                ('group', models.CharField(max_length=8, verbose_name='\u56e2\u961f')),
                ('eqmanage', models.IntegerField(default=0, verbose_name='\u8bbe\u5907\u7ba1\u7406')),
                ('assistant', models.IntegerField(default=0, verbose_name='\u5916\u822a\u52a9\u7406')),
                ('groupleader', models.IntegerField(default=0, verbose_name='\u7ec4\u957f')),
                ('typing', models.IntegerField(default=0, verbose_name='\u6253\u5b57')),
                ('counting', models.IntegerField(default=0, verbose_name='\u6570\u7968')),
                ('accountmanage', models.IntegerField(default=0, verbose_name='\u8d22\u52a1')),
                ('courseware', models.IntegerField(default=0, verbose_name='\u8bfe\u4ef6\u5236\u4f5c')),
                ('skill', models.IntegerField(default=0, verbose_name='\u6280\u80fd\u6570')),
                ('spoints', models.IntegerField(default=0, verbose_name='\u6280\u80fd\u52a0\u5206')),
                ('selfchecky', models.IntegerField(default=0, verbose_name='\u81ea\u67e5\u5408\u683c')),
                ('selfcheckn', models.IntegerField(default=0, verbose_name='\u81ea\u67e5\u4e0d\u5408\u683c')),
                ('scpoints', models.IntegerField(default=0, verbose_name='\u81ea\u67e5\u5f97\u5206')),
                ('smileservy', models.IntegerField(default=0, verbose_name='\u5fae\u7b11\u5408\u683c')),
                ('smileservn', models.IntegerField(default=0, verbose_name='\u5fae\u7b11\u4e0d\u5408\u683c')),
                ('sspoints', models.IntegerField(default=0, verbose_name='\u5fae\u7b11\u5f97\u5206')),
                ('cspraiseletters', models.IntegerField(default=0, verbose_name='\u5357\u822a\u8868\u626c\u4fe1')),
                ('othpraiseletters', models.IntegerField(default=0, verbose_name='\u5916\u822a\u8868\u626c\u4fe1')),
                ('plpoints', models.IntegerField(default=0, verbose_name='\u8868\u626c\u4fe1\u5f97\u5206')),
                ('fivestars', models.IntegerField(default=0, verbose_name='\u4e94\u661f')),
                ('threestars', models.IntegerField(default=0, verbose_name='\u4e09\u661f')),
                ('starpoints', models.IntegerField(default=0, verbose_name='\u4e94\u661f\u5f97\u5206')),
                ('lateshow', models.IntegerField(default=0, verbose_name='\u8fdf\u5230')),
                ('lspoints', models.IntegerField(default=0, verbose_name='\u8fdf\u5230\u6263\u5206')),
                ('sickleave', models.IntegerField(default=0, verbose_name='\u75c5\u5047')),
                ('slpoints', models.IntegerField(default=0, verbose_name='\u75c5\u5047\u6263\u5206')),
                ('fullattendance', models.IntegerField(default=2, verbose_name='\u5168\u52e4')),
                ('publicity', models.IntegerField(default=0, verbose_name='\u5ba3\u4f20\u62a5\u9053')),
                ('ppoints', models.IntegerField(default=0, verbose_name='\u5ba3\u4f20\u62a5\u9053\u5f97\u5206')),
                ('complaint', models.IntegerField(default=0, verbose_name='\u6295\u8bc9')),
                ('cpoints', models.IntegerField(default=0, verbose_name='\u6295\u8bc9\u6263\u5206')),
                ('nocomplaint', models.IntegerField(default=1, verbose_name='\u65e0\u6295\u8bc9')),
                ('mistakelv1', models.IntegerField(default=0, verbose_name='\u4e00\u822c\u5dee\u9519')),
                ('mistakelv2', models.IntegerField(default=0, verbose_name='\u4e2d\u7b49\u5dee\u9519')),
                ('mistakelv3', models.IntegerField(default=0, verbose_name='\u4e25\u91cd\u5dee\u9519')),
                ('mtpoints', models.IntegerField(default=0, verbose_name='\u5dee\u9519\u6263\u5206')),
                ('nomistake', models.IntegerField(default=5, verbose_name='\u65e0\u5dee\u9519')),
                ('total', models.IntegerField(default=0, verbose_name='\u6700\u7ec8\u5f97\u5206')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='\u8d77\u59cb\u65f6\u95f4')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='\u622a\u6b62\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u4e2a\u4eba\u5f97\u5206',
                'verbose_name_plural': '\u4e2a\u4eba\u5f97\u5206',
            },
        ),
    ]
