# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-27 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datalib',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u5e8f\u53f7')),
                ('case_title', models.CharField(max_length=30, verbose_name='\u6807\u9898')),
                ('case_type', models.CharField(choices=[('\u503c\u673a\u5dee\u9519', '\u503c\u673a\u5dee\u9519'), ('\u884c\u674e\u6258\u8fd0', '\u503c\u673a\u6258\u8fd0')], max_length=10, verbose_name='\u7c7b\u578b')),
                ('direct_liability', models.CharField(max_length=18, verbose_name='\u76f4\u63a5\u8d23\u4efb\u4eba')),
                ('indirect_liability', models.CharField(max_length=26, verbose_name='\u7ba1\u7406\u8d23\u4efb\u4eba')),
                ('case_content', models.TextField(max_length=800, verbose_name='\u6848\u4f8b\u5185\u5bb9')),
                ('improvement', models.TextField(max_length=400, verbose_name='\u6574\u6539\u63aa\u65bd')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='\u65e5\u671f')),
            ],
            options={
                'verbose_name': '\u503c\u673a\u6848\u4f8b\u5e93',
                'verbose_name_plural': '\u503c\u673a\u6848\u4f8b\u5e93',
            },
        ),
    ]
