# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-23 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datalib',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False, verbose_name='\u5e8f\u53f7')),
                ('case_title', models.CharField(max_length=50, verbose_name='\u6807\u9898')),
                ('case_type', models.CharField(choices=[('\u8bc1\u4ef6\u9519/\u6f0f\u67e5\u9a8c', '\u8bc1\u4ef6\u9519/\u6f0f\u67e5\u9a8c'), ('\u9519\u63a5/\u53d1\u3001\u6f0f\u63a5/\u53d1\u767b\u673a\u724c', '\u9519\u63a5/\u53d1\u3001\u6f0f\u63a5/\u53d1\u767b\u673a\u724c'), ('\u9519\u8f93\u884c\u674e\u91cd\u91cf', '\u9519\u8f93\u884c\u674e\u91cd\u91cf'), ('\u9519\u8f93\u884c\u674e\u76ee\u7684\u5730', '\u9519\u8f93\u884c\u674e\u76ee\u7684\u5730'), ('\u9519\u51cf\u884c\u674e', '\u9519\u51cf\u884c\u674e'), ('\u672a\u56de\u6536\u9500\u6bc1\u5e9f\u65e7\u884c\u674e\u724c', '\u672a\u56de\u6536\u9500\u6bc1\u5e9f\u65e7\u884c\u674e\u724c'), ('\u672a\u56de\u6536\u751f\u4ea7\u7269\u8d44', '\u672a\u56de\u6536\u751f\u4ea7\u7269\u8d44')], max_length=30, verbose_name='\u7c7b\u578b')),
                ('direct_liability', models.CharField(max_length=18, verbose_name='\u76f4\u63a5\u8d23\u4efb\u4eba')),
                ('indirect_liability', models.CharField(max_length=26, verbose_name='\u95f4\u63a5\u8d23\u4efb\u4eba')),
                ('destination', models.CharField(max_length=3, verbose_name='\u6700\u7ec8\u76ee\u7684\u56fd\u5bb6\u4e09\u5b57\u7801')),
                ('case_content', models.TextField(max_length=800, verbose_name='\u6848\u4f8b\u5185\u5bb9')),
                ('case_analysis', models.TextField(max_length=800, verbose_name='\u539f\u56e0\u5206\u6790')),
                ('improvement', models.TextField(max_length=400, verbose_name='\u6574\u6539\u63aa\u65bd')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='\u65e5\u671f')),
            ],
            options={
                'verbose_name': '\u6848\u4f8b',
                'verbose_name_plural': '\u503c\u673a\u6848\u4f8b\u5e93',
            },
        ),
    ]
