# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-27 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalib', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datalib',
            options={'verbose_name': '\u6458\u8981', 'verbose_name_plural': '\u503c\u673a\u6848\u4f8b\u5e93'},
        ),
        migrations.AddField(
            model_name='datalib',
            name='case_analysis',
            field=models.TextField(default=0, max_length=800, verbose_name='\u539f\u56e0\u5206\u6790'),
            preserve_default=False,
        ),
    ]
