# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-28 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalib', '0002_auto_20160827_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datalib',
            name='case_type',
            field=models.CharField(choices=[('\u503c\u673a\u5dee\u9519', '\u503c\u673a\u5dee\u9519'), ('\u884c\u674e\u6258\u8fd0', '\u884c\u674e\u6258\u8fd0')], max_length=10, verbose_name='\u7c7b\u578b'),
        ),
    ]
